### PR TITLE
Open editor with arguments

### LINKED ISSUE #56: Open editor with arguments
Thank you for great application.

My RedMine supports markdown.
So I want to open editor with filetype setting like: `vim -c "set filetype=markdown"`.

- Version: ec81c0f (self-built)

### PR DESCRIPTION
**Pull request by Omochice**
Resolve #56.

But I'm new to golang.
If I write bad code, Please point it.

### CODE REVIEW

**Comment by mattn** [comment]
Thanks. Please keep editor and parse string as strings with using https://github.com/mattn/go-shellwords.

**Comment by Omochice** [comment]
OK, I will try it.

**Comment by Omochice** [comment]
I made specifiable `editor` field like: `vim -c "filetype=markdown"` by changing `GetEditor` function.

How about this?

**Comment by mattn** [comment]
Looks good. It is my expected code. Thank you.

**Pull request merged**
